# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "puppet-labs-centos64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  config.vm.network :private_network, ip: "192.168.33.101"
  config.vm.host_name = "pptmaster.local"

  #config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--memory", "1024"]
  #end
 
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "master.pp"
  end
 
end
